# Used for development
version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 10000:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin123
      MYSQL_USER: admin
      MYSQL_DATABASE: pearshop
      MYSQL_PORT: 3306
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]

