env: localhost
port: 10001
id_hasher:
  min_length: 16
  salt: super-secret
mysql:
  masters: localhost:10000
  slaves: localhost:10000
  user: admin
  password: admin123
  db: pearshop
  max_open_conns: 5
  max_idle_conns: 5
  conn_max_lifetime: 60
  is_enable_log: false
jwt_secret: super-jwt-secret

