// Code generated by MockGen. DO NOT EDIT.
// Source: hashid.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIDHasher is a mock of IDHasher interface.
type MockIDHasher struct {
	ctrl     *gomock.Controller
	recorder *MockIDHasherMockRecorder
}

// MockIDHasherMockRecorder is the mock recorder for MockIDHasher.
type MockIDHasherMockRecorder struct {
	mock *MockIDHasher
}

// NewMockIDHasher creates a new mock instance.
func NewMockIDHasher(ctrl *gomock.Controller) *MockIDHasher {
	mock := &MockIDHasher{ctrl: ctrl}
	mock.recorder = &MockIDHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDHasher) EXPECT() *MockIDHasherMockRecorder {
	return m.recorder
}

// Decode mocks base method.
func (m *MockIDHasher) Decode(hashed string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", hashed)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockIDHasherMockRecorder) Decode(hashed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockIDHasher)(nil).Decode), hashed)
}

// Encode mocks base method.
func (m *MockIDHasher) Encode(id int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", id)
	ret0, _ := ret[0].(string)
	return ret0
}

// Encode indicates an expected call of Encode.
func (mr *MockIDHasherMockRecorder) Encode(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockIDHasher)(nil).Encode), id)
}
